name: Deployment

on: workflow_dispatch

jobs:
    build: 
        runs-on : ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: node js install
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: install dep
              run: npm install
            - name: npm build
              run: npm run build
            - name: npm test
              run: npm run test
            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with: 
                name: my-artifiact
                path : /
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with: 
                name: my-artifact
            - name: deploying to webapp
              run: echo deploying to Webapp
