name: Deployment

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
    build: 
        env:
          VAR1: ${{vars.VAR1}}
          SECRET1: ${{secrets.SECRET1}}
        runs-on : ubuntu-latest
        outputs:
            script-file: ${{ steps.publish.outputs.script-file}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: node js install
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: print varaiable1 and secret1
              run: 
                echo $VAR1
                echo $SECRET1

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: install dep
              run: npm install
            - name: npm build
              run: npm run build
            - name: npm test
              run: npm run test
            - name: Publish JS filename
              id: publish
              run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with: 
                name: my-artifact
                path : dist
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with: 
                name: my-artifact
            - name: list files
              run: ls -l
            - name: Output filename
              run: echo "${{ needs.build.outputs.script-file }}"
            - name: deploying to webapp
              run: echo deploying to Webapp
