name: first workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:

  first-job:
      runs-on : self-hosted
      steps:
        - name: echo hello
          run: echo "hello 👋"
  second-job:
    runs-on : win-agent-CI-01
    steps:
      - name: echo hello
        run: |
          echo hello
          echo hello2
