name: first-workflow

on:
    workflow_dispatch

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: echo hello
    deploy:
        runs-on: ubuntu-lates
        steps:
            - name: hello 2
              run: |
                echo hellow 
                echo hellowww
