name: npm ci workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout files
        uses: actions/checkout@v4
      - name: npm install dependencies
        run: npm install
      - name: npm build step
        run:  npm run build  
      - name: npm tests
        run:  npm run test   